apiVersion: batch/v1
kind: Job
metadata:
  name: earthworks-db-migrate
  namespace: earthworks
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 900
  template:
    spec:
      shareProcessNamespace: true
      restartPolicy: Never
      containers:
      - name: dbmate
        image: stephenhillier/earthworks-api:IMAGE_VERSION
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["sleep 3; /app/dbmate -e DB_CONN -d /app/db/migrations migrate; exit_code=$?; pkill -INT /usr/local/bin/pilot-agent; exit $exit_code"]
        env:
          - name: DBHOST
            valueFrom:
              configMapKeyRef:
                name: earthworks-db
                key: host
          - name: DBPORT
            valueFrom:
              configMapKeyRef:
                name: earthworks-db
                key: port
          - name: DBPASS
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_CONN
            value: postgres://$(DBUSER):$(DBPASS)@$(DBHOST):$(DBPORT)/geo?sslmode=require
