<template>
  <b-container fluid id="dashboard" class="mb-3">
    <b-row>
      <b-col cols="12" lg="3" xl="2" class="mt-3">
        <project-select></project-select>
      </b-col>
      <b-col class="mt-3">
        <b-card>
<p>          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum. Rutrum tellus pellentesque eu tincidunt. Vel risus commodo viverra maecenas accumsan lacus vel facilisis volutpat. Urna id volutpat lacus laoreet non curabitur. Pharetra vel turpis nunc eget lorem dolor sed. Euismod quis viverra nibh cras. Ac turpis egestas integer eget aliquet. Et pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Lectus magna fringilla urna porttitor rhoncus dolor purus non. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Placerat duis ultricies lacus sed turpis. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Pellentesque habitant morbi tristique senectus et netus et. Cursus eget nunc scelerisque viverra mauris in. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Elementum pulvinar etiam non quam lacus.</p>
<p>Vitae suscipit tellus mauris a diam maecenas sed enim ut. Vitae et leo duis ut diam quam. Nec feugiat nisl pretium fusce. Lectus arcu bibendum at varius vel pharetra vel turpis. Netus et malesuada fames ac turpis. Magnis dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Vitae nunc sed velit dignissim sodales ut eu. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Feugiat nisl pretium fusce id velit ut. Mauris nunc congue nisi vitae suscipit tellus mauris. Convallis a cras semper auctor neque vitae. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Arcu dictum varius duis at. A cras semper auctor neque vitae tempus quam pellentesque nec. Morbi leo urna molestie at elementum. Ut sem nulla pharetra diam.</p>
<p>Imperdiet proin fermentum leo vel orci porta non. Mi sit amet mauris commodo quis imperdiet massa. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Elementum facilisis leo vel fringilla est ullamcorper eget. Volutpat blandit aliquam etiam erat velit. In hac habitasse platea dictumst quisque sagittis. Sit amet mattis vulputate enim. Etiam erat velit scelerisque in dictum non consectetur a. Enim ut tellus elementum sagittis vitae et. Integer malesuada nunc vel risus. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Dictum fusce ut placerat orci nulla pellentesque dignissim enim sit. Mattis aliquam faucibus purus in massa tempor nec feugiat. Id eu nisl nunc mi ipsum. Quisque id diam vel quam elementum pulvinar. Mollis nunc sed id semper.</p>
<p>Turpis egestas integer eget aliquet nibh. Tortor posuere ac ut consequat semper. A lacus vestibulum sed arcu. Purus ut faucibus pulvinar elementum integer. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Sit amet tellus cras adipiscing enim eu. Turpis cursus in hac habitasse platea dictumst quisque sagittis. Nunc non blandit massa enim nec. Scelerisque in dictum non consectetur. Felis eget velit aliquet sagittis. Pretium fusce id velit ut tortor pretium. Cursus turpis massa tincidunt dui. Aenean vel elit scelerisque mauris pellentesque. Nulla malesuada pellentesque elit eget. Vitae semper quis lectus nulla at volutpat. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Fringilla urna porttitor rhoncus dolor purus non enim praesent.</p>
<p>Scelerisque in dictum non consectetur. Felis donec et odio pellentesque diam volutpat. Egestas sed tempus urna et. Suspendisse ultrices gravida dictum fusce. Dolor magna eget est lorem ipsum dolor. Lobortis feugiat vivamus at augue eget arcu. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Quam id leo in vitae turpis massa. Diam phasellus vestibulum lorem sed risus ultricies. Sed risus ultricies tristique nulla aliquet enim tortor.</p>
<p>Congue quisque egestas diam in arcu cursus euismod quis viverra. Nunc non blandit massa enim nec dui nunc mattis enim. Eu lobortis elementum nibh tellus molestie nunc non. Vel facilisis volutpat est velit egestas dui id ornare. Pretium lectus quam id leo in. Non sodales neque sodales ut etiam sit. Luctus accumsan tortor posuere ac. Imperdiet dui accumsan sit amet nulla facilisi morbi. Tortor id aliquet lectus proin. Massa enim nec dui nunc. Phasellus vestibulum lorem sed risus ultricies tristique nulla. A cras semper auctor neque vitae tempus quam. Enim diam vulputate ut pharetra sit amet aliquam id. Morbi tincidunt augue interdum velit. At auctor urna nunc id cursus. Magna fringilla urna porttitor rhoncus. Blandit libero volutpat sed cras ornare arcu dui. Quis auctor elit sed vulputate mi sit amet. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum.</p>
<p>Cras fermentum odio eu feugiat pretium nibh ipsum consequat. Sed sed risus pretium quam vulputate. Eget mi proin sed libero enim sed faucibus turpis in. Consectetur adipiscing elit ut aliquam purus sit. Purus semper eget duis at tellus at. Massa tincidunt nunc pulvinar sapien et ligula. Sed egestas egestas fringilla phasellus. Neque viverra justo nec ultrices dui sapien eget mi. Turpis egestas maecenas pharetra convallis posuere morbi leo. Nunc consequat interdum varius sit. Blandit aliquam etiam erat velit scelerisque in dictum non. Proin libero nunc consequat interdum varius. Non quam lacus suspendisse faucibus interdum. Non consectetur a erat nam at lectus urna. Cursus turpis massa tincidunt dui. In nisl nisi scelerisque eu ultrices vitae. Gravida neque convallis a cras semper auctor.</p>
<p>Sit amet cursus sit amet. Euismod elementum nisi quis eleifend. Nisl tincidunt eget nullam non nisi est. Ut porttitor leo a diam sollicitudin. Nulla pharetra diam sit amet nisl suscipit. Elit at imperdiet dui accumsan sit amet nulla facilisi. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Ultrices neque ornare aenean euismod. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Pulvinar elementum integer enim neque volutpat ac. Turpis egestas sed tempus urna et pharetra. Tempor orci dapibus ultrices in. Semper quis lectus nulla at volutpat.</p>
<p>Tincidunt nunc pulvinar sapien et ligula. Felis bibendum ut tristique et egestas quis. Nibh mauris cursus mattis molestie a. Elit ut aliquam purus sit amet. Aliquet porttitor lacus luctus accumsan tortor. At varius vel pharetra vel turpis nunc eget. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in. Fermentum dui faucibus in ornare quam viverra. Sem viverra aliquet eget sit amet tellus cras. Faucibus interdum posuere lorem ipsum. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Sit amet aliquam id diam maecenas ultricies mi. At elementum eu facilisis sed odio morbi quis commodo. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Odio ut sem nulla pharetra diam. Purus in mollis nunc sed id semper. Leo vel orci porta non pulvinar neque laoreet suspendisse interdum.</p>
<p>Et netus et malesuada fames ac turpis. Tincidunt ornare massa eget egestas purus viverra. Purus in mollis nunc sed id semper risus. Consequat ac felis donec et odio pellentesque. Suspendisse in est ante in nibh mauris cursus mattis. Lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam ut porttitor leo. Ultrices eros in cursus turpis. Et tortor consequat id porta nibh. Sed augue lacus viverra vitae. Ut tellus elementum sagittis vitae. Et leo duis ut diam. Sem integer vitae justo eget magna fermentum iaculis eu non. Egestas fringilla phasellus faucibus scelerisque eleifend donec. Et odio pellentesque diam volutpat commodo sed egestas egestas. Egestas integer eget aliquet nibh praesent tristique magna sit.</p>
        </b-card>
      </b-col>
    </b-row>
  </b-container>
</template>

<script>
import ProjectSelect from '@/components/dashboard/ProjectSelect.vue'
export default {
  name: 'Dashboard',
  components: {
    ProjectSelect
  }
}
</script>

<style>

</style>
