# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plotsvc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='plotsvc.proto',
  package='plotsvc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rplotsvc.proto\x12\x07plotsvc\"\x12\n\x10SievePlotRequest\"/\n\x11SievePlotResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06\x66igure\x18\x02 \x01(\t2Q\n\tSievePlot\x12\x44\n\tPlotSieve\x12\x19.plotsvc.SievePlotRequest\x1a\x1a.plotsvc.SievePlotResponse\"\x00\x62\x06proto3')
)




_SIEVEPLOTREQUEST = _descriptor.Descriptor(
  name='SievePlotRequest',
  full_name='plotsvc.SievePlotRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=44,
)


_SIEVEPLOTRESPONSE = _descriptor.Descriptor(
  name='SievePlotResponse',
  full_name='plotsvc.SievePlotResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='plotsvc.SievePlotResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='figure', full_name='plotsvc.SievePlotResponse.figure', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['SievePlotRequest'] = _SIEVEPLOTREQUEST
DESCRIPTOR.message_types_by_name['SievePlotResponse'] = _SIEVEPLOTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SievePlotRequest = _reflection.GeneratedProtocolMessageType('SievePlotRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIEVEPLOTREQUEST,
  __module__ = 'plotsvc_pb2'
  # @@protoc_insertion_point(class_scope:plotsvc.SievePlotRequest)
  ))
_sym_db.RegisterMessage(SievePlotRequest)

SievePlotResponse = _reflection.GeneratedProtocolMessageType('SievePlotResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIEVEPLOTRESPONSE,
  __module__ = 'plotsvc_pb2'
  # @@protoc_insertion_point(class_scope:plotsvc.SievePlotResponse)
  ))
_sym_db.RegisterMessage(SievePlotResponse)



_SIEVEPLOT = _descriptor.ServiceDescriptor(
  name='SievePlot',
  full_name='plotsvc.SievePlot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=95,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='PlotSieve',
    full_name='plotsvc.SievePlot.PlotSieve',
    index=0,
    containing_service=None,
    input_type=_SIEVEPLOTREQUEST,
    output_type=_SIEVEPLOTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIEVEPLOT)

DESCRIPTOR.services_by_name['SievePlot'] = _SIEVEPLOT

# @@protoc_insertion_point(module_scope)
