apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: earthworks-api
    app: earthworks-api
  name: earthworks-api
  namespace: earthworks
spec:
  replicas: 1
  selector:
    matchLabels:
      run: earthworks-api
      app: earthworks-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: earthworks-api
        app: earthworks-api
        version: v1
    spec:
      containers:
      - name: earthworks-api
        image: stephenhillier/earthworks-api
        ports:
        - containerPort: 8000
        resources: {}
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=islandcivil-223001:us-west1:islandcivil-db=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
status: {}
