apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: earthworks-api
    app: earthworks-api
  name: earthworks-api
  namespace: earthworks
spec:
  replicas: 1
  selector:
    matchLabels:
      run: earthworks-api
      app: earthworks-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: earthworks-api
        app: earthworks-api
        version: v1
    spec:
      containers:
      - name: earthworks-api
        image: stephenhillier/earthworks-api
        ports:
        - containerPort: 8000
        resources: {}
        env:
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=islandcivil-223001:us-west1:islandcivil-db=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: earthworks-api
  name: earthworks-api
  namespace: earthworks
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: earthworks-api
status:
  loadBalancer: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: earthworks-api-gateway
  namespace: earthworks
  labels:
    app: earthworks-api
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - earthworks.islandcivil.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: earthworks-api
  namespace: earthworks
  labels:
    app: earthworks-api
spec:
  hosts:
  - earthworks.islandcivil.com
  gateways:
  - earthworks-api-gateway
  http:
  - match:
    - uri:
        prefix: "/api/v1"
    route:
    - destination:
        host: earthworks-api
        port:
          number: 8000
